MaerskLine/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MaerskLine.Models;
using Microsoft.AspNet.Identity;

namespace MaerskLine.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext dbContext;

        public CustomerController()
        {
            dbContext = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            dbContext.Dispose();
        }

        // GET: Customer
        [Authorize]
        public ActionResult CustomerForm()
        {
            return View();
        }

        [Authorize]
        public ActionResult SaveCustomer(Customer customer)
        {
            var currentUser = User.Identity.Name;

            if (customer.CustID == 0)
            {
                customer.CustAgent = currentUser;

                dbContext.Customers.Add(customer);
            }
            else
            {
                var custInDB = dbContext.Customers.SingleOrDefault(c => c.CustID == customer.CustID);

                custInDB.CustName = customer.CustName;
                custInDB.CustPhoneNum = customer.CustPhoneNum;
                custInDB.CustEmail = customer.CustEmail;
            }

            dbContext.SaveChanges();

            TempData["CustomerSuccessMsg"] = true;

            if (User.IsInRole("Admin"))
            {
                var customerList = dbContext.Customers.ToList();

                return View("ViewCustomer", customerList);
            }
            else
            {
                var customerList = dbContext.Customers.Where(c => c.CustAgent == User.Identity.Name).ToList();

                return View("ViewCustomer", customerList);
            }

        }

        [Authorize]
        public ActionResult ViewCustomer()
        {
            TempData["CustomerSuccessMsg"] = false;

            if (User.IsInRole("Admin"))
            {
                var cust = dbContext.Customers.ToList();
                return View(cust);
            }
            else
            {
                var cust = dbContext.Customers.Where(c => c.CustAgent == User.Identity.Name).ToList();
                return View(cust);
            }
        }

        [Authorize]
        public ActionResult EditCustomer(int custID)
        {
            var cust = dbContext.Customers.SingleOrDefault(c => c.CustID == custID);

            if (cust == null)
            {
                return HttpNotFound();
            }

            Customer custModel = new Customer();
            custModel.CustID = cust.CustID;
            custModel.CustName = cust.CustName;
            custModel.CustPhoneNum = cust.CustPhoneNum;
            custModel.CustEmail = cust.CustEmail;

            return View("CustomerForm", custModel);
        }
    }
}

MaerskLine/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MaerskLine.Models;
using MaerskLine.ViewModel;
using System.Diagnostics;

namespace MaerskLine.Controllers
{
    public class OrderController : Controller
    {
        private ApplicationDbContext dbContext;

        public OrderController()
        {
            dbContext = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            dbContext.Dispose();
        }

        // GET: Order
        [Authorize]
        public ActionResult SelectSchedule()
        {
            var schedule = dbContext.Schedules.Include(s => s.Ship).Where(s => s.ScheduleAvailability.Equals(true)).ToList();

            return View(schedule);
        }

        [Authorize]
        public ActionResult SelectCustomer(int scheduleID)
        {
            var schedule = dbContext.Schedules.Include(s => s.Ship).SingleOrDefault(c => c.ScheduleID == scheduleID);

            var customer = dbContext.Customers.Where(c => c.CustAgent == User.Identity.Name).ToList();

            ScheduleCustomerOrderViewModel scovm = new ScheduleCustomerOrderViewModel()
            {
                Schedule = schedule,
                Customers = customer
            };

            return View(scovm);
        }

        [Authorize]
        public ActionResult OrderForm(int custID, int scheduleID)
        {
            TempData["OrderFailMsg"] = false;

            var customer = dbContext.Customers.SingleOrDefault(c => c.CustID == custID);

            var schedule = dbContext.Schedules.Include(s => s.Ship).SingleOrDefault(c => c.ScheduleID == scheduleID);

            ScheduleCustomerOrderViewModel scovm = new ScheduleCustomerOrderViewModel()
            {
                Schedule = schedule,
                Customer = customer
            };

            return View(scovm);
        }

        [Authorize]
        public ActionResult SaveOrder(ScheduleCustomerOrderViewModel scovm)
        {
            var order = new Order
            {
                ScheduleID = scovm.Schedule.ScheduleID,
                CustID = scovm.Customer.CustID,
                OrderAgent = User.Identity.Name
            };

            var container = new Container()
            {
                ContainerID = scovm.Container.ContainerID,
                ContainerItem = scovm.Container.ContainerItem,
                ContainerNum = scovm.Container.ContainerNum,
                ContainerWeight = scovm.Container.ContainerWeight,
                OrderID = scovm.Order.OrderID
            };

            var getContainerNum = dbContext.Ships.SingleOrDefault(c => c.ShipID == scovm.Schedule.ShipID);

            if (container.ContainerNum > getContainerNum.ShipContainerNumRemaining || container.ContainerNum == 0)
            {
                // false

                TempData["OrderFailMsg"] = true;

                return View("OrderForm", scovm);
            }
            else
            {
                getContainerNum.ShipContainerNumRemaining -= scovm.Container.ContainerNum;

                dbContext.Orders.Add(order);

                dbContext.Containers.Add(container);

                dbContext.SaveChanges();

                TempData["OrderSuccessMsg"] = true;

                //var orderList = dbContext.Orders.Include(s => s.Schedule.Ship).Include(s => s.Schedule).Include(c => c.Customer).ToList();
                if (User.IsInRole("Admin"))
                {
                    var orderList = dbContext.Containers.Include(o => o.Order).Include(s => s.Order.Schedule)
                        .Include(s => s.Order.Schedule.Ship).Include(s => s.Order.Customer).ToList();

                    return View("ViewOrder",orderList);
                }
                else
                {
                    var orderList = dbContext.Containers.Include(o => o.Order).Include(s => s.Order.Schedule)
                        .Include(s => s.Order.Schedule.Ship).Include(s => s.Order.Customer).Where(o => o.Order.OrderAgent == User.Identity.Name).ToList();

                    return View("ViewOrder",orderList);
                }
            }

        }

        [Authorize]
        public ActionResult ViewOrder()
        {
            TempData["OrderSuccessMsg"] = false;

            if (User.IsInRole("Admin"))
            {
                var orderList = dbContext.Containers.Include(o => o.Order).Include(s => s.Order.Schedule)
                    .Include(s => s.Order.Schedule.Ship).Include(s => s.Order.Customer).ToList();

                return View(orderList);
            }
            else
            {
                var orderList = dbContext.Containers.Include(o => o.Order).Include(s => s.Order.Schedule)
                    .Include(s => s.Order.Schedule.Ship).Include(s => s.Order.Customer).Where(o => o.Order.OrderAgent == User.Identity.Name).ToList();

                return View(orderList);
            }

        }

    }
}

MaerskLine/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MaerskLine.Models;
using Microsoft.Ajax.Utilities;

namespace MaerskLine.Controllers
{
    public class ScheduleController : Controller
    {
        private ApplicationDbContext dbContext;

        public ScheduleController()
        {
            dbContext = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            dbContext.Dispose();
        }

        // GET: Schedule
        [Authorize(Roles = "Admin")]
        public ActionResult ScheduleForm()
        {
            var shipList = dbContext.Ships.Where(s => s.ShipAvailability.Equals(true)).ToList();
            var viewModel = new ShipScheduleViewModal
            {
                Ships = shipList

            };

            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult SaveSchedule(ShipScheduleViewModal ssvm)
        {
            if (ssvm.Schedule.ScheduleID == 0)
            {
                var scheduleDB = ssvm.Schedule;

                dbContext.Schedules.Add(scheduleDB);
            }
            else
            {
                var scheduleInDB = dbContext.Schedules.Include(s => s.Ship).SingleOrDefault(c => c.ScheduleID == ssvm.Schedule.ScheduleID);

                scheduleInDB.ScheduleOrigin = ssvm.Schedule.ScheduleOrigin;
                scheduleInDB.ScheduleDestination = ssvm.Schedule.ScheduleDestination;
                scheduleInDB.ScheduleDepartureDateTime = ssvm.Schedule.ScheduleDepartureDateTime;
                scheduleInDB.ScheduleArrivalDateTime = ssvm.Schedule.ScheduleArrivalDateTime;
                scheduleInDB.ShipID = ssvm.Schedule.ShipID;
                scheduleInDB.ScheduleAvailability = ssvm.Schedule.ScheduleAvailability;
            }

            dbContext.SaveChanges();

            TempData["ScheduleSuccessMsg"] = true;

            var scheduleList = dbContext.Schedules.Include(s => s.Ship).ToList();

            return View("ViewSchedule", scheduleList);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ViewSchedule()
        {
            TempData["ScheduleSuccessMsg"] = false;

            var schedule = dbContext.Schedules.Include(s => s.Ship).ToList();

            return View(schedule);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditSchedule(int scheduleID)
        {
            var schedule = dbContext.Schedules.Include(s => s.Ship).SingleOrDefault(c => c.ScheduleID == scheduleID);

            if (schedule == null)
            {
                return HttpNotFound();
            }

            ShipScheduleViewModal ssvm = new ShipScheduleViewModal
            {
                Schedule = schedule,
                Ships = dbContext.Ships.DistinctBy(s => s.ShipName).Where(s => s.ShipAvailability.Equals(true)).ToList()
                
            };
            //ssvm.Schedule.ScheduleID = scheduleID;
            //ssvm.Schedule.ScheduleOrigin = schedule.ScheduleOrigin;
            //ssvm.Schedule.ScheduleDestination = schedule.ScheduleDestination;
            //ssvm.Schedule.ScheduleDepartureDateTime = schedule.ScheduleDepartureDateTime;
            //ssvm.Schedule.ScheduleArrivalDateTime = schedule.ScheduleArrivalDateTime;
            //ssvm.Schedule.ShipID = schedule.ShipID;
            //ssvm.Schedule.ScheduleAvailability = schedule.ScheduleAvailability;

            return View("ScheduleForm", ssvm);
        }
    }
}

MaerskLine/Controllers/ShipController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MaerskLine.Models;

namespace MaerskLine.Controllers
{
    public class ShipController : Controller
    {
        private ApplicationDbContext dbContext;

        public ShipController()
        {
            dbContext = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            dbContext.Dispose();
        }

        // GET: Ship
        [Authorize(Roles = "Admin")]
        public ActionResult ShipForm()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult SaveShip(Ship ship)
        {
            if (ship.ShipID == 0)
            {
                ship.ShipContainerNumRemaining = ship.ShipContainerNum;

                dbContext.Ships.Add(ship);
            }
            else
            {
                var shipInDB = dbContext.Ships.SingleOrDefault(c => c.ShipID == ship.ShipID);

                //shipInDB.ShipID = ship.ShipID;
                shipInDB.ShipName = ship.ShipName;
                shipInDB.ShipContainerNum = ship.ShipContainerNum;
                shipInDB.ShipContainerNumRemaining = shipInDB.ShipContainerNumRemaining;
                shipInDB.ShipAvailability = ship.ShipAvailability;
            }
            
            dbContext.SaveChanges();

            ViewBag.ShipSuccessMsg = true;

            var shipList = dbContext.Ships.ToList();

            return View("ViewShip", shipList);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ViewShip()
        {
            ViewBag.ShipSuccessMsg = false;

            var ship = dbContext.Ships.ToList();

            return View(ship);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditShip(int shipID)
        {
            var ship = dbContext.Ships.SingleOrDefault(c => c.ShipID == shipID);

            if (ship == null)
            {
                return HttpNotFound();
            }

            Ship shipModel = new Ship();
            shipModel.ShipID = ship.ShipID;
            shipModel.ShipName = ship.ShipName;
            shipModel.ShipContainerNum = ship.ShipContainerNum;
            //shipModel.ShipOrigin = ship.ShipOrigin;
            //shipModel.ShipDestination = ship.ShipDestination;
            //shipModel.ShipDepartingTime = ship.ShipDepartingTime;
            //shipModel.ShipArrivingTime = ship.ShipArrivingTime;
            shipModel.ShipAvailability = ship.ShipAvailability;

            return View("ShipForm", shipModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteShip()
        {
            return View();
        }


    }
}

MaerskLine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Maersk Line", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    
                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ship<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Add Ship", "ShipForm", "Ship")</li>
                                    <li>@Html.ActionLink("View Ship", "ViewShip", "Ship")</li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Schedule<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Add Schedule", "ScheduleForm", "Schedule")</li>
                                    <li>@Html.ActionLink("View Schedule", "ViewSchedule", "Schedule")</li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Customer<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("View Customer", "ViewCustomer", "Customer")</li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Order<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("View Order", "ViewOrder", "Order")</li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Customer<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Add Customer", "CustomerForm", "Customer")</li>
                                    <li>@Html.ActionLink("View Customer", "ViewCustomer", "Customer")</li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Order<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Add Order", "SelectSchedule", "Order")</li>
                                    <li>@Html.ActionLink("View Order", "ViewOrder", "Order")</li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        
        @if (!User.Identity.IsAuthenticated)
        {
            <br/>
            <p>Please Login to Proceed! :)</p>
        }
        else
        {
            if (User.IsInRole("Admin"))
            {
                <h3>Admin</h3>

                <div class="row">
                    <div class="col-md-3">
                        <h4>Manage Ship</h4>
                        <ul>
                            @*name,action,controller*@
                            <li>@Html.ActionLink("Add Ship", "ShipForm", "Ship")</li>
                            <li>@Html.ActionLink("View Ship", "ViewShip", "Ship")</li>
                            @*<li>@Html.ActionLink("DeleteShip", "DeleteShip", "Ship")</li>*@
                        </ul>
                    </div>

                    <div class="col-md-3">
                        <h4>Manage Schedule</h4>
                        <ul>
                            @*name,action,controller*@
                            <li>@Html.ActionLink("Add Schedule", "ScheduleForm", "Schedule")</li>
                            <li>@Html.ActionLink("View Schedule", "ViewSchedule", "Schedule")</li>
                        </ul>
                    </div>
                    
                    <div class="col-md-3">
                        <h4>Manage Customer</h4>
                        <ul>
                            @*name,action,controller*@
                            @*<li>@Html.ActionLink("Add Customer", "CustomerForm", "Customer")</li>*@
                            <li>@Html.ActionLink("View Customer", "ViewCustomer", "Customer")</li>
                            @*<li>@Html.ActionLink("DeleteShip", "DeleteShip", "Ship")</li>*@
                        </ul>
                    </div>

                    <div class="col-md-3">
                        <h4>Manage Order</h4>
                        <ul>
                            @*name,action,controller*@
                            @*<li>@Html.ActionLink("Add Order", "SelectSchedule", "Order")</li>*@
                            <li>@Html.ActionLink("View Order", "ViewOrder", "Order")</li>
                            @*<li>@Html.ActionLink("DeleteShip", "DeleteShip", "Ship")</li>*@
                        </ul>
                    </div>
                </div>

            }
            else
            {
                <h1>Agent</h1>

                <div class="row">
                    <div class="col-md-4">
                        <h4>Manage Customer</h4>
                        <ul>
                            @*name,action,controller*@
                            <li>@Html.ActionLink("Add Customer", "CustomerForm", "Customer")</li>
                            <li>@Html.ActionLink("View Customer", "ViewCustomer", "Customer")</li>
                            @*<li>@Html.ActionLink("DeleteShip", "DeleteShip", "Ship")</li>*@
                        </ul>
                    </div>

                    <div class="col-md-4">
                        <h4>Manage Order</h4>
                        <ul>
                            @*name,action,controller*@
                            <li>@Html.ActionLink("Add Order", "SelectSchedule", "Order")</li>
                            <li>@Html.ActionLink("View Order", "ViewOrder", "Order")</li>
                            @*<li>@Html.ActionLink("DeleteShip", "DeleteShip", "Ship")</li>*@
                        </ul>
                    </div>
                </div>
            }
        }

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Maersk Line</p>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>